### PR TITLE
Added support for door opening/closing delay

### PR DESCRIPTION
**Pull request by Spartan-II-117**

### CODE REVIEW

**Comment by Spartan-II-117** [comment]
fixes #5

**Comment by jerrod-lankford** [comment]
So I agree that avoiding double triggering is nice, but im not sure what will happen to HA if you report the state as opening and closing. AFAIK they only use opened and closed. I will have to test this. Also theres a few code things that need to change as well

**Comment by Spartan-II-117** [comment]
This does not report back to HASS, just handles it internally, also, I did not write most of the code changes, as you can see rom the commit history, @anotherdirtbag did most of the work.

**Comment by jerrod-lankford** [comment]
@Spartan-II-117 It could actually report back to hass. What happens is whenever the pin state changes on the rPi I read the door.state and publish that to mqtt. If the timeout is set for too long then the state could be reported as closing and in fact it would never get reported as acutally closed unless more code was added to account for this.

**Comment by Spartan-II-117** [comment]
We could simply remove the code that reports to HA, since it's not looking for those States anyway

**Comment by anotherdirtbag** [comment]
After looking more at https://home-assistant.io/components/cover.mqtt/ it doesn't look as simple as I assumed to turn this into a 3 state switch (open/closed/neither). I could report the % open as "tilt" which would be cool but not useful since the "cover" is still either open or closed.

**Comment by anotherdirtbag** [comment]
Given all of that, I'm thinking the best way would be to somehow create a thread that changes the state after the timeout has finished. I've never successfully used threads with python, so we'll see if i'm even able to figure it out.

**Pull request closed without merging**
