### PR TITLE
Autostart and relay invert

### PR DESCRIPTION
**Pull request by tagno25**
I added support for inverting the relay logic (new default is relay pin off by default), and created an autostart script for systemd.
I also changed the config file from using the working directory to using the same directory as the main.py file.

### CODE REVIEW

**Comment by jerrod-lankford** [comment]
I haven't forgotten about the PR. Thanks for this! I want to test it before I merge but I've been busy lately. I'll try to get to it tomorrow.

**Comment by tagno25** [comment]
Had to add a few lines to the service file to restart after a crash, because if the MQTT server was unresponsive the service would crash.

**Comment by tagno25** [comment]
have you tested this PR?

**Comment by jerrod-lankford** [comment]
@tagno25 I have not had a chance to test this PR I'm so sorry. I promise ill check it out this weekend :)

**Comment by jerrod-lankford** [comment]
I left one comment. When that is resolved i will merge the PR.

**Comment by tagno25** [comment]
I have not been able to find the comment with the issue.

**Comment by jerrod-lankford** [comment]
I was just asking if line five of autostart_systemd.sh should be changed from:

systemctl enable home-assistant@\`whoami\`

to

systemctl enable garageqtpi@\`whoami\`.service

**Comment by tagno25** [comment]
It doesn't have to have the .service at the end, but it may make it simpler to read and understand...

Fixing now

**Comment by jerrod-lankford** [comment]
But its home-assist@\`whoami\`. Shouldnt it be garageqtpi@\`whoami\`?

**Comment by jerrod-lankford** [comment]
Excellent thanks. Merging

**Comment by tagno25** [comment]
Sorry, I noticed that it had the wrong service name after making the previous comment

**Comment by jerrod-lankford** [comment]
Np! Thanks again

**Pull request merged**
